export const USER_PRIMARYACCOUNT_REQUEST = "USER_PRIMARYACCOUNT_REQUEST";
export const USER_PRIMARYACCOUNT_SUCCESS = "USER_PRIMARYACCOUNT_SUCCESS";
export const USER_PRIMARYACCOUNT_FAIL = "USER_PRIMARYACCOUNT_FAIL";

export const USER_SAVINGSACCOUNT_REQUEST = "USER_SAVINGSACCOUNT_REQUEST";
export const USER_SAVINGSACCOUNT_SUCCESS = "USER_SAVINGSACCOUNT_SUCCESS";
export const USER_SAVINGSACCOUNT_FAIL = "USER_SAVINGSACCOUNT_FAIL";
