export const USER_APPOINTMENT_REQUEST = "USER_APPOINTMENT_REQUEST";
export const USER_APPOINTMENT_SUCCESS = "USER_APPOINTMENT_SUCCESS";
export const USER_APPOINTMENT_FAIL = "USER_APPOINTMENT_FAIL";
export const USER_APPOINTMENT_SIGNOUT = "USER_APPOINTMENT_SIGNOUT";