export const TRANSFER_BETWEEN_ACCOUNT_REQUEST = "TRANSFER_BETWEEN_ACCOUNT_REQUEST";
export const TRANSFER_BETWEEN_ACCOUNT_SUCCESS = "TRANSFER_BETWEEN_ACCOUNT_SUCCESS";
export const TRANSFER_BETWEEN_ACCOUNT_FAIL = "TRANSFER_BETWEEN_ACCOUNT_FAIL";
export const TRANSFER_BETWEEN_ACCOUNT_SIGNOUT = "TRANSFER_BETWEEN_ACCOUNT_SIGNOUT";

export const TRANSFER_TOSOMEONELSE_REQUEST = "TRANSFER_TOSOMEONELSE_REQUEST";
export const TRANSFER_TOSOMEONELSE_SUCCESS = "TRANSFER_TOSOMEONELSE_SUCCESS";
export const TRANSFER_TOSOMEONELSE_FAIL = "TRANSFER_TOSOMEONELSE_FAIL";
export const TRANSFER_TOSOMEONELSE_SIGNOUT = "TRANSFER_TOSOMEONELSE_SIGNOUT";

export const TRANSFER_EDITADDRECIPIENT_REQUEST = "TRANSFER_EDITADDRECIPIENT_REQUEST";
export const TRANSFER_EDITADDRECIPIENT_SUCCESS = "TRANSFER_EDITADDRECIPIENT_SUCCESS";
export const TRANSFER_EDITADDRECIPIENT_FAIL = "TRANSFER_EDITADDRECIPIENT_FAIL";
export const TRANSFER_EDITADDRECIPIENT_SIGNOUT = "TRANSFER_EDITADDRECIPIENT_SIGNOUT";

export const TRANSFER_ADDRECIPIENT_REQUEST = "TRANSFER_ADDRECIPIENT_REQUEST";
export const TRANSFER_ADDRECIPIENT_SUCCESS = "TRANSFER_ADDRECIPIENT_SUCCESS";
export const TRANSFER_ADDRECIPIENT_FAIL = "TRANSFER_ADDRECIPIENT_FAIL";
export const TRANSFER_ADDRECIPIENT_SIGNOUT = "TRANSFER_ADDRECIPIENT_SIGNOUT";