export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST";
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL";
export const USER_SIGNOUT = "USER_SIGNOUT";

export const USER_SIGNUP_REQUEST = "USER_SIGNUP_REQUEST";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_FAIL = "USER_SIGNUP_FAIL";

export const USER_UPDATE_REQUEST ="USER_UPDATE_REQUEST"
export const  USER_UPDATE_SUCCESS =" USER_UPDATE_SUCCESS";
export const  USER_UPDATE_FAIL="USER_UPDATE_FAIL";

export const TRANSFER_BALANCE_FATCH_REQUEST = "TRANSFER_BALANCE_FATCH_REQUEST";
export const TRANSFER_BALANCE_FATCH_SUCCESS = "TRANSFER_BALANCE_FATCH_SUCCESS";
export const TRANSFER_BALANCE_FATCH_FAIL = "TRANSFER_BALANCE_FATCH_FAIL";
export const TRANSFER_BALANCE_FATCH_SIGNOUT = "TRANSFER_BALANCE_FATCH_SIGNOUT";
