export const ADMIN_APPOINTMENT_REQUEST = "ADMIN_APPOINTMENT_REQUEST";
export const ADMIN_APPOINTMENT_SUCCESS = "ADMIN_APPOINTMENT_SUCCESS";
export const ADMIN_APPOINTMENT_FAIL    = "ADMIN_APPOINTMENT_FAIL";